version: '3'
services: 

  mysql:
    image: mysql
    cap_add: 
      - SYS_NICE
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: user
    ports: 
      - "3306:3306"